# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69c65a8a12aac296e051aa1370cadfe77739d42eae60ec59d385d6ea1b30bb8434732bdbcf762ea5c3b971dcc5623db71c39638bae3162b244ff32b28691420c

test:
  secret_key_base: bed53e003b6454e81b7acdfdadcdbb71b02fe4484cad8aa8937b697858a3a475c660166f0cf9e98de3fe98d81b53d8536b6c57abcd9ca6cbec8c70a7e50ed5e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
